commandTopic: cmd_vel
odometryTopic: odom
odometryFrame: odom
robotBaseFrame: robot_footprint
publishWheelTF: false
publishOdomTF: true
publishWheelJointState: false
wheelseparation: 0.35
wheelDiameter: .20
wheelAcceleration: 0.0
WheelTorque: 5.0
updateRate: 50.0
odometrySource: world

